server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:

  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rapidboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

#    #초기 데이터 저장용!!!
#    initialization-mode: always

  jpa:
    open-in-view: true
    #FetchType Lazy

    properties:
      hibernate:
        ddl-auto: none # create, none, update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true

    show-sql: true

logging:
  level:
    org:
      apache:
        http: DEBUG